#:schema node_modules/wrangler/config-schema.json
# wrangler.toml
name = 'minecraftmotd' # 你的项目名称
main = "index.js"            # 入口文件
compatibility_date = "2024-05-01"

# 1. [vars] - 环境变量 (例如：API 地址、配置开关)
[vars]
API_URL = "https://api.example.com"
ENVIRONMENT = "production"


[[kv_namespaces]]
binding = "MOTD_KV"    # <--- 这里改成了 MOTD_KV
id = "1c5896227cbc4ca09e7a30e27a39fddc"      # 保持你创建的 KV ID 不变



# 3. [[r2_buckets]] - R2 对象存储绑定
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "你的桶名称"

# 4. [[d1_databases]] - D1 数据库绑定
# [[d1_databases]]
# binding = "DB"
# database_name = "你的数据库名"
# database_id = "这里填入你的数据库ID"

# 5. [observability] - 开启日志监控 (推荐)
[observability]
enabled = true
